spring:
  application:
    name: auth
  datasource:
    url: jdbc:h2:mem:sparta
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  secret-key: Zj9$wQmE6vNp#TgYxR2uL1bC7aVh0XzK
  access-exp: 3600000
  refresh-exp: 1209600000


server:
  port: 8080

